### ISSUE TITLE
Workflow incompatible

### ISSUE THREAD

**Issue by ferreirafabio** [xfslove/alfred-google-translate#68] opened 2020-06-01 10:17 UTC
When I download the workflow v2.0.8 and import it into my Alfred v3.8.6 on Mac OS 10.15, Alfred tells me "Workflow incompatible. Please update the latest version of Alfred." However, this workflow is supposed to work on Alfred 3 and 4.

I have the Powerpack, Node.js 8+, and the alfred-language-configuration installed.

**Comment by xfslove** [comment] 2020-06-02 01:07
You should Try install with npm by `npm install -g alfred-google-translate`

**Comment by ferreirafabio** [comment] 2020-06-02 08:23
That does give me an error too:

> $ sudo npm install -g alfred-google-translate
> 
> > alfred-google-translate@2.0.8 postinstall /usr/local/lib/node_modules/alfred-google-translate
> > alfy-init
> 
> Error: Command failed with exit code 1 (EPERM): alfred-link
>     at makeError (/usr/local/lib/node_modules/alfred-google-translate/node_modules/execa/lib/error.js:59:11)
>     at handlePromise (/usr/local/lib/node_modules/alfred-google-translate/node_modules/execa/index.js:112:26)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async /usr/local/lib/node_modules/alfred-google-translate/node_modules/alfy/init.js:7:3 {
>   command: 'alfred-link',
>   exitCode: 1,
>   exitCodeName: 'EPERM',
>   stdout: '',
>   stderr: 'Error: Permission denied to read Alfred preferences at location /Users/user/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
>     '    at module.exports (/usr/local/lib/node_modules/alfred-google-translate/node_modules/resolve-alfred-prefs/index.js:44:9)',
>   all: 'Error: Permission denied to read Alfred preferences at location /Users/user/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
>     '    at module.exports (/usr/local/lib/node_modules/alfred-google-translate/node_modules/resolve-alfred-prefs/index.js:44:9)',
>   failed: true,
>   timedOut: false,
>   isCanceled: false,
>   killed: false,
>   signal: undefined
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! alfred-google-translate@2.0.8 postinstall: `alfy-init`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the alfred-google-translate@2.0.8 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/user/.npm/_logs/2020-06-02T08_22_24_743Z-debug.log

**Comment by ferreirafabio** [comment] 2020-06-02 08:58
How can I download the workflow manually for the correct version?

**Comment by xfslove** [comment] 2020-06-02 09:32
See the error log:

```
Error: Permission denied to read Alfred preferences at location: /Users/user/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
```
it caused by permission issue, please check the permission of this directory.

The release page does not have v3 workflows. I export v3 for you, you could have a try.

The alfred-google-translate and afred-language-configuration archive ([workflows.zip](https://github.com/xfslove/alfred-google-translate/files/4716154/workflows.zip)).
but I recommend you install with npm for get updates in time.

**Comment by xfslove** [comment] 2020-07-08 01:55
Hi, @ferreirafabio if you could working with the workflow, I'll close this issue. you could reopen it or raise a new one when you have any questions.

**Closed by xfslove** 2020-07-08 01:55 UTC
